title: "Archil Jain's Contributions Blog"
email: archil@example.com
description: >- 
  Open source contributions, GSoC-style progress logs, and dev writeups.
baseurl: ""
url: "https://Archiljain.github.io"
theme: remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache